### ISSUE TITLE
taskcat update is creating s3 buckets with private permissions

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroachdb-cloudformation#23]
2018-09-21 14:47:45,257 [DEBUG] Retrieving contents from https://taskcat-tag-cockroachdb-cloudformation-6f85bea3.s3.amazonaws.com/cockroachdb-cloudfor
mation/scripts/awslogs.service
2018-09-21 14:47:45,605 [ERROR] Error encountered during build of master-setup: Failed to retrieve https://taskcat-tag-cockroachdb-cloudformation-6f85
bea3.s3.amazonaws.com/cockroachdb-cloudformation/scripts/awslogs.service: HTTP Error 403 : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>715C0F185808F54E</RequestId><HostId>7Xqdl9/eKGHxpvDH81oibjauX0/fh6snzDrEntj
f6Lriosok3YJAE61VJkkS437jjte+Lf9B1Mw=</HostId></Error>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 251, in build
    changes['files'] = FileTool().apply(self._config.files, self._auth_config)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/file_tool.py", line 138, in apply
    self._write_file(f, attribs, auth_config)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/file_tool.py", line 225, in _write_file
    raise ToolError("Failed to retrieve %s: %s" % (source, e.strerror))
ToolError: Failed to retrieve https://taskcat-tag-cockroachdb-cloudformation-6f85bea3.s3.amazonaws.com/cockroachdb-cloudformation/scripts/awslogs.serv
ice: HTTP Error 403 : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>715C0F185808F54E</RequestId><HostId>7Xqdl9/eKGHxpvDH81oibjauX0/fh6snzDrEntj
f6Lriosok3YJAE61VJkkS437jjte+Lf9B1Mw=</HostId></Error>

**Comment by nstewart** [comment]
looks like there is a new flag `-p` to make these public. `taskcat -c cockroachdb-cloudformation/ci/config.yml -n -p`
